# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcgRouter < Formula
  desc "Unified local router for Claude Code and Codex CLI"
  homepage "https://github.com/XZXY-AI/ccg-router"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/XZXY-AI/ccg-router/releases/download/v0.3.0/ccg-router_0.3.0_darwin_amd64.tar.gz"
      sha256 "eb789b8a3b0735abe74411ec3ef66305b40cd7f3e1dfa58cf2c79bcae9a59b35"

      define_method(:install) do
        bin.install "ccg-router"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/XZXY-AI/ccg-router/releases/download/v0.3.0/ccg-router_0.3.0_darwin_arm64.tar.gz"
      sha256 "b4acee4172df79ecdca5873cab97688cb3ca71cfb876cb36424985c16c7034cb"

      define_method(:install) do
        bin.install "ccg-router"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/XZXY-AI/ccg-router/releases/download/v0.3.0/ccg-router_0.3.0_linux_amd64.tar.gz"
      sha256 "6baf0f6f6fb233f0ae3eba0cb2d1440f6604aa4e7944040b00a4953fad15517f"
      define_method(:install) do
        bin.install "ccg-router"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/XZXY-AI/ccg-router/releases/download/v0.3.0/ccg-router_0.3.0_linux_arm64.tar.gz"
      sha256 "a0995cbb68400d3b2114f993a0b1d232b3d3214fadbb2b9d7a67f8b2e2ef26e1"
      define_method(:install) do
        bin.install "ccg-router"
      end
    end
  end
end
