# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcgRouter < Formula
  desc "Unified local router for Claude Code and Codex CLI"
  homepage "https://github.com/XZXY-AI/ccg-router"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/XZXY-AI/ccg-router/releases/download/v0.1.0/ccg-router_0.1.0_darwin_amd64.tar.gz"
      sha256 "2a6f5088cd7760359c5c75571452d6aefb523310394e05e4840b3d6087bc16de"

      define_method(:install) do
        bin.install "ccg-router"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/XZXY-AI/ccg-router/releases/download/v0.1.0/ccg-router_0.1.0_darwin_arm64.tar.gz"
      sha256 "e50caabfa376ec430339acc54a32db16d23b67ced94dfc85caa7732ded64e9a3"

      define_method(:install) do
        bin.install "ccg-router"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/XZXY-AI/ccg-router/releases/download/v0.1.0/ccg-router_0.1.0_linux_amd64.tar.gz"
      sha256 "4cba4ad01f71e2f53cf5eedbe72df6cd509d10c71f1819fcc5c8ce5c2c577398"
      define_method(:install) do
        bin.install "ccg-router"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/XZXY-AI/ccg-router/releases/download/v0.1.0/ccg-router_0.1.0_linux_arm64.tar.gz"
      sha256 "9c10494495771cb214c42d00775cc03e86ed3070dda746e5f1533df22f0c85a5"
      define_method(:install) do
        bin.install "ccg-router"
      end
    end
  end
end
